#SIEMPRE PRINT STATEMENT 
#BUSQUEDA BINARIA: ME VOY A LA MITAD, HASTA AQUI FUNCIONA BIEN, PERFECTO, YA SE QUE EN ESTA MITAD NO ESTA EL ERROR, VAMOS A LA OTRA MITAD
#LLEVAR REGISTRO DE TODO LO QUE HACES PARA TRARAR EL BUG
#SI NO LO CONSIGUES, VETA A DORMIR Y NO TE FRUSTRES!!!!

